Algoritmo "criarOC"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var
   Gen, Num:Inteiro
   Fundo: Caractere
Inicio
    Escreval("Escolha um Gênero: (Digite apenas o número)")
    EscrevaL("1 - [Mulher], 2- [Homem], 3- [Gênero Fluido]")
    Leia(Gen)
    Escreval("Escolha um número de 1-7:")
    Leia(Num)
    Escreval("Prefere Noite ou Dia?")
    Leia(fundo)
    
    


Fimalgoritmo